baseurl = "https://blog.wallaroolabs.com"
languageCode = "en-us"
title = "Wallaroo Labs Engineering"
theme = "sendence-hugo-steam-theme"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 5

[permalinks]
  post = "/:year/:month/:title/"

[params]
	title = "Wallaroo Labs"
	subtitle = "\"I wanna go fast\""
	copyright = ""

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []
  logo      = "img/logo_horiz.png"

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Wallaroo Labs"
	bio = ""
	description = "Official blog of the Wallaroo Labs Engineering team"

	# Link your social networks (optional)
	location = ""
	twitter = "wallaroolabs"
	linkedin = "WallarooLabs"
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "WallarooLabs"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
	useSummaryIfNoDescription = true

[menu]

  [[menu.main]]
    name = "All Topics"
    # pre = "<i class='fa fa-road'></i>"
    url = "/tags/"
    weight = -100

  [[menu.main]]
    name = "Python"
    # pre = "<i class='fa fa-road'></i>"
    url = "/tags/python/"
    weight = -90

  [[menu.main]]
    name = "Performance"
    # pre = "<i class='fa fa-road'></i>"
    url = "/tags/performance/"
    weight = -80

  [[menu.main]]
    name = "Examples"
    # pre = "<i class='fa fa-road'></i>"
    url = "/tags/example/"
    weight = -70

  # [[menu.main]]
  #   name = "" # Save for later, if client wants to implement search
  #   pre = "<i class='fa fa-search fa-flip-horizontal'></i>"
  #   url = "/tags/search/"
  #   weight = -60

  [[menu.splash]]
    name = "Star me on GitHub"
    pre = "<i class='fa fa-github bounce'></i>"
    url = "https://github.com/wallaroolabs/wallaroo"
    weight = -100

  [[menu.splash]]
    name = "Answer our 30-second survey, and be entered to win a Wallaroo T-Shirt"
    pre = "<i class='fa fa-check bounce'></i>"
    url = "https://wallaroolabs.typeform.com/to/HS6azY?source=wallaroo_blog"
    weight = -90
